### ISSUE TITLE
Make identity poop out column headers

### ISSUE THREAD

**Issue by stringerbell** [dstockto/csv-chef#1]
Running `csv-chef identity ./foo.csv`

This returns something like:
```
1 <- 1
2 <- 2
3 <- 3
...
```
It seems like it'd be handy to have annotated names, like such as:
```
1 <- 1 # voter id
2 <- 2 # first
3 <- 3 # last
...
```

**Comment by dstockto** [comment]
Did you mean with header output turned on, or either way?

**Comment by stringerbell** [comment]
ooh -- yes. I'm mostly just getting used to this and poking around. I think I'm imagining not having to always reference the input file manually if you forget which index maps to which column

**Comment by dstockto** [comment]
I like the comment idea though. Could be helpful.
