### ISSUE TITLE
Add option to skip and report csv lines with the wrong number of fields

### ISSUE THREAD

**Issue by dstockto** [dstockto/csv-chef#22]
Sometimes I'm getting CSVs that are not properly formatted (commas in data fields that are not quoted usually). This results in a single error about he line with the wrong number of fields, but then it just stops. For large files (millions of lines) there may be 1000s of these errors. It would be good to let the processing finish, possibly skipping the bad lines, but printing out that they are bad so I can find and fix all the problems with the source in one shot rather than one line, run, error, fix, run, error, fix, 1000s of times.

**Comment by stringerbell** [comment]
I would love this too

**Comment by Guitarbum722** [comment]
👍

**Comment by dstockto** [comment]
Closed with #30 - or technically sort of before that. It was skipping and reporting. #30 allows you to choose if you're prefer it to exit with an error on a CSV parse error, or continue on without writing out the bad line.
