### ISSUE TITLE
Add force option for identity

### ISSUE THREAD

**Issue by stringerbell** [dstockto/csv-chef#4]
smoll nit:
I want to be able to force overwrite my starting recipe, so I'd like a way to force overwrite the output, just like bake has

Repro:
`$ csv-chef identity ./foo.csv -o ./recipe.csv`
`$ csv-chef identity ./foo.csv -o ./recipe.csv` 
The second one fails with:
```2021/09/01 20:33:00 ERROR: Output file already exists: ./recipe.csv```

**Comment by dstockto** [comment]
Closed with #8
