### ISSUE TITLE
Have public recipes

### ISSUE THREAD

**Issue by stringerbell** [dstockto/csv-chef#5]
Use case I'm imagining:

- I am a GME stonks trader, and I get my information from $PUBLIC_DATA_SOURCE
- I know about a $PUBLIC_DATA_SOURCE recipe from here that gets my data whipped into some format I really like
- I can plug a public recipe into a github action or some other favorite way of working, and make a pipeline I like

**Comment by dstockto** [comment]
Seems like putting those in another repo would be the way to go?

**Comment by stringerbell** [comment]
I'd imagine so!

**Comment by dstockto** [comment]
This is a thing now too: https://github.com/dstockto/csv-chef-recipes
